language: python

services:
    - elasticsearch

python:
    - "2.6"
    - "2.7"

notifications:
    email: false

install:
    - virtualenv .
    - ./bin/pip install -r requirements/dev.txt

script:
    - ./bin/python run_tests.py
